name: Deploy to Azure Container Registry

on:
  push:
    branches: [ "main" ]
    paths:
      - 'autorent-api-usuarios/**'
      - 'autorent-api-vehiculos/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to Azure Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.AZURE_ACR_LOGIN_SERVER }}
          username: ${{ secrets.AZURE_ACR_USERNAME }}
          password: ${{ secrets.AZURE_ACR_PASSWORD }}

      - name: Build and push Usuarios
        working-directory: ./autorent-api-usuarios
        run: |
          docker build -t ${{ secrets.AZURE_ACR_LOGIN_SERVER }}/usuarios:latest .
          docker push ${{ secrets.AZURE_ACR_LOGIN_SERVER }}/usuarios:latest

      - name: Build and push Vehiculos
        working-directory: ./autorent-api-vehiculos
        run: |
          docker build -t ${{ secrets.AZURE_ACR_LOGIN_SERVER }}/vehiculos:latest .
          docker push ${{ secrets.AZURE_ACR_LOGIN_SERVER }}/vehiculos:latest
