name: Deploy all services to Azure ACR on PR to main

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  build-and-push:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.AZURE_ACR_LOGIN_SERVER }}
          username: ${{ secrets.AZURE_ACR_USERNAME }}
          password: ${{ secrets.AZURE_ACR_PASSWORD }}

      - name: Build and push Usuarios
        working-directory: ./autorent-api-usuarios
        run: |
          docker build -t ${{ secrets.AZURE_ACR_LOGIN_SERVER }}/usuarios:latest \
            --build-arg NODE_ENV=production .
          docker push ${{ secrets.AZURE_ACR_LOGIN_SERVER }}/usuarios:latest

      - name: Build and push Vehiculos
        working-directory: ./autorent-api-vehiculos
        run: |
          docker build -t ${{ secrets.AZURE_ACR_LOGIN_SERVER }}/vehiculos:latest \
            --build-arg NODE_ENV=production .
          docker push ${{ secrets.AZURE_ACR_LOGIN_SERVER }}/vehiculos:latest

      - name: Build and push Gateway
        working-directory: ./autorent-api-gateway
        run: |
          docker build -t ${{ secrets.AZURE_ACR_LOGIN_SERVER }}/gateway:latest \
            --build-arg NODE_ENV=production .
          docker push ${{ secrets.AZURE_ACR_LOGIN_SERVER }}/gateway:latest

      - name: Build and push Cliente
        working-directory: ./autorent-cliente
        run: |
          docker build -t ${{ secrets.AZURE_ACR_LOGIN_SERVER }}/cliente:latest \
            --build-arg NODE_ENV=production .
          docker push ${{ secrets.AZURE_ACR_LOGIN_SERVER }}/cliente:latest
